version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile.${NODE_ENV:-development}
    restart: always
    init: true
    env_file:
      - .env

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - ./data/db:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER:-user}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-password}
      WORDPRESS_DB_NAME: db
    depends_on:
      - db

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - 80:8000
      - 443:8000
    volumes:
      - ./docker/nginx/custom.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - wordpress
